// Generated by 'unplugin-auto-import'
export {}
declare global {
<<<<<<< HEAD

=======
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
>>>>>>> e3d8d121b3c19e91e2b39cc57de75d74a436f18e
}
